BEGIN;
UPDATE inventory SET min_price_ur = 837, min_price_it = 821, min_price_reg = 794 WHERE name = 'Acacia Honey 250GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Dal Chana 200GM';
UPDATE inventory SET min_price_ur = 188, min_price_it = 185, min_price_reg = 185 WHERE name = 'Dal Moong 200GM';
UPDATE inventory SET min_price_ur = 180, min_price_it = 176, min_price_reg = 176 WHERE name = 'Dal Moth 200GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Fiery Chicken Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Gathia 200GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Hot Sizzling Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Ketchup Tango Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 42, min_price_it = 41, min_price_reg = 41 WHERE name = 'Khatta Meetha Mix (Mini) 40GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Khatta Meetha Mix 200GM';
UPDATE inventory SET min_price_ur = 42, min_price_it = 41, min_price_reg = 41 WHERE name = 'Mix Nimco (Mini) 40GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Badam Kheer Mix 155GM';
UPDATE inventory SET min_price_ur = 166, min_price_it = 163, min_price_reg = 163 WHERE name = 'Red Chilli Powder 100GM';
UPDATE inventory SET min_price_ur = 93, min_price_it = 92, min_price_reg = 92 WHERE name = 'Red Chilli Powder 50GM';
UPDATE inventory SET min_price_ur = 154, min_price_it = 151, min_price_reg = 151 WHERE name = 'Turmeric Powder 100GM';
UPDATE inventory SET min_price_ur = 81, min_price_it = 80, min_price_reg = 80 WHERE name = 'Turmeric Powder 50GM';
UPDATE inventory SET min_price_ur = 242, min_price_it = 238, min_price_reg = 238 WHERE name = 'White Pepper Powder 50GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Hyderabadi Pulao 25GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Mughlai Qorma 25GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Peshawari Karahi 25GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Riwaiti Achar Gosht 25GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Special Tikka 25GM';
UPDATE inventory SET min_price_ur = 49, min_price_it = 48, min_price_reg = 48 WHERE name = 'Traditional Bombay Biryani 30GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Malai Boti 60GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Authentic Sindhi Biryani 120GM';
UPDATE inventory SET min_price_ur = 154, min_price_it = 151, min_price_reg = 151 WHERE name = 'Broast Mix 125GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Chapli Kabab Masala 100GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Chicken Masala 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Daighi Beef Biryani 60GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Delhi Nihari 60GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Fish Masala 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Fried Fish 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Haleem Masala 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Hyderabadi Pulao 65GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Karachi Biryani Masala 60GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Koyla Karhai 40GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Mughlai Qorma 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Paya Masala 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Peshawari Karahi 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Riwaiti Achar Gosht 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Shahi Seekh Kabab 50GM';
UPDATE inventory SET min_price_ur = 130, min_price_it = 127, min_price_reg = 127 WHERE name = 'Bread Crumbs 200GM';
UPDATE inventory SET min_price_ur = 38, min_price_it = 37, min_price_reg = 37 WHERE name = 'Miswak';
UPDATE inventory SET min_price_ur = 62, min_price_it = 61, min_price_reg = 59 WHERE name = 'Baking Powder 50GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Banana Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Blackcurrant Flavor Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Blueberry Flavor Jelly 80GM';
UPDATE inventory SET min_price_ur = 140, min_price_it = 137, min_price_reg = 133 WHERE name = 'Cocoa Powder 50GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Corn Flour 250GM';
UPDATE inventory SET min_price_ur = 626, min_price_it = 614, min_price_reg = 614 WHERE name = 'Chocolate Cake Rusk 350GM';
UPDATE inventory SET min_price_ur = 401, min_price_it = 393, min_price_reg = 393 WHERE name = 'Classic Chocolate Cookies 240GM';
UPDATE inventory SET min_price_ur = 335, min_price_it = 328, min_price_reg = 328 WHERE name = 'Cumin Delight Cookies 200GM';
UPDATE inventory SET min_price_ur = 293, min_price_it = 287, min_price_reg = 287 WHERE name = 'Cumin Puff Pastry 200GM';
UPDATE inventory SET min_price_ur = 293, min_price_it = 287, min_price_reg = 287 WHERE name = 'Lazo Puff Pastry 200GM';
UPDATE inventory SET min_price_ur = 293, min_price_it = 287, min_price_reg = 287 WHERE name = 'Palmiers Puff Pastry 200GM';
UPDATE inventory SET min_price_ur = 335, min_price_it = 328, min_price_reg = 328 WHERE name = 'Strawberry Jam Cookies 200GM';
UPDATE inventory SET min_price_ur = 10163, min_price_it = 9964, min_price_reg = 9964 WHERE name = 'Steam Pre Clean (Ziafat) 25KG';
UPDATE inventory SET min_price_ur = 1099, min_price_it = 1077, min_price_reg = 1077 WHERE name = 'Biryani Masala 1KG';
UPDATE inventory SET min_price_ur = 827, min_price_it = 810, min_price_reg = 810 WHERE name = 'Tikka Boti 1KG';
UPDATE inventory SET min_price_ur = 845, min_price_it = 829, min_price_reg = 829 WHERE name = 'Peshawari Karahi Masala 1KG';
UPDATE inventory SET min_price_ur = 756, min_price_it = 741, min_price_reg = 741 WHERE name = 'Riwaiti Achar Gosht 1KG';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Cream Caramel 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Kheer Mix 155GM';
UPDATE inventory SET min_price_ur = 140, min_price_it = 137, min_price_reg = 133 WHERE name = 'Mango Custard 250GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Mango Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Mango Pudding Mix 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Orange Flavor Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Pineapple Flavor Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Pista Kheer Mix 155GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Pistachio Pudding Mix 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Pudding Mix 80GM';
UPDATE inventory SET min_price_ur = 189, min_price_it = 185, min_price_reg = 179 WHERE name = 'Rabri Flavor Falooda 220GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Raspberry Flavor Jelly 80GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Raspberry Pudding Mix 80GM';
UPDATE inventory SET min_price_ur = 185, min_price_it = 181, min_price_reg = 175 WHERE name = 'Sheer Khurma 160GM';
UPDATE inventory SET min_price_ur = 140, min_price_it = 137, min_price_reg = 133 WHERE name = 'Strawberry Custard 250GM';
UPDATE inventory SET min_price_ur = 124, min_price_it = 121, min_price_reg = 117 WHERE name = 'Strawberry Jelly 80GM';
UPDATE inventory SET min_price_ur = 140, min_price_it = 137, min_price_reg = 133 WHERE name = 'Vanila Custard 250GM';
UPDATE inventory SET min_price_ur = 140, min_price_it = 137, min_price_reg = 133 WHERE name = 'Chocolate Custard 90GM';
UPDATE inventory SET min_price_ur = 169, min_price_it = 165, min_price_reg = 160 WHERE name = 'Gelatine Powder 50GM';
UPDATE inventory SET min_price_ur = 189, min_price_it = 185, min_price_reg = 179 WHERE name = 'Rasmalai 75Gm';
UPDATE inventory SET min_price_ur = 189, min_price_it = 185, min_price_reg = 179 WHERE name = 'Strawberry Flavor Falooda 220GM';
UPDATE inventory SET min_price_ur = 312, min_price_it = 306, min_price_reg = 296 WHERE name = 'Fried Onion 400GM';
UPDATE inventory SET min_price_ur = 499, min_price_it = 489, min_price_reg = 489 WHERE name = 'Ispaghol 95GM';
UPDATE inventory SET min_price_ur = 77, min_price_it = 76, min_price_reg = 76 WHERE name = 'Meat Tenderizer 40GM';
UPDATE inventory SET min_price_ur = 198, min_price_it = 194, min_price_reg = 187 WHERE name = 'Pheni 200GM';
UPDATE inventory SET min_price_ur = 39, min_price_it = 38, min_price_reg = 37 WHERE name = 'Vermicelli 100GM';
UPDATE inventory SET min_price_ur = 55, min_price_it = 53, min_price_reg = 52 WHERE name = 'Vermicelli 150GM';
UPDATE inventory SET min_price_ur = 664, min_price_it = 651, min_price_reg = 630 WHERE name = 'Blackseed Oil 125ML';
UPDATE inventory SET min_price_ur = 473, min_price_it = 464, min_price_reg = 449 WHERE name = 'Castor Oil 125ML';
UPDATE inventory SET min_price_ur = 473, min_price_it = 464, min_price_reg = 449 WHERE name = 'Coconut Oil 125ML';
UPDATE inventory SET min_price_ur = 473, min_price_it = 464, min_price_reg = 449 WHERE name = 'Mustard Oil 125ML';
UPDATE inventory SET min_price_ur = 473, min_price_it = 464, min_price_reg = 449 WHERE name = 'Sesame Oil 125ML';
UPDATE inventory SET min_price_ur = 1542, min_price_it = 1512, min_price_reg = 1462 WHERE name = 'Sidr Honey 250GM';
UPDATE inventory SET min_price_ur = 2637, min_price_it = 2585, min_price_reg = 2501 WHERE name = 'Sidr Honey 500GM';
UPDATE inventory SET min_price_ur = 45, min_price_it = 44, min_price_reg = 44 WHERE name = 'Refined Salt 800GM';
UPDATE inventory SET min_price_ur = 42, min_price_it = 41, min_price_reg = 41 WHERE name = 'Black Pepper Potato Sticks (Mini) 40GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Black Pepper Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Chaat Papri 200GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Dahi Boondi 200GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Nimco Mix 200GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Peri Crunch Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Salty Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 171, min_price_it = 168, min_price_reg = 168 WHERE name = 'Spicy Potato Sticks 180GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Bareek Boondi 200GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Dahi Phulki 200GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Masala Papri 200GM';
UPDATE inventory SET min_price_ur = 2672, min_price_it = 2619, min_price_reg = 2534 WHERE name = 'Extra Virgin Olive Oil 500ML';
UPDATE inventory SET min_price_ur = 2290, min_price_it = 2245, min_price_reg = 2172 WHERE name = 'Virgin Olive Oil 500ML';
UPDATE inventory SET min_price_ur = 328, min_price_it = 322, min_price_reg = 311 WHERE name = 'Garlic Paste 330GM';
UPDATE inventory SET min_price_ur = 655, min_price_it = 642, min_price_reg = 621 WHERE name = 'Garlic Paste 750GM';
UPDATE inventory SET min_price_ur = 323, min_price_it = 316, min_price_reg = 316 WHERE name = 'Ginger Garlic 330GM';
UPDATE inventory SET min_price_ur = 644, min_price_it = 632, min_price_reg = 632 WHERE name = 'Ginger Garlic 750GM';
UPDATE inventory SET min_price_ur = 371, min_price_it = 364, min_price_reg = 364 WHERE name = 'Ginger Paste 330GM';
UPDATE inventory SET min_price_ur = 644, min_price_it = 632, min_price_reg = 632 WHERE name = 'Ginger Paste 750GM';
UPDATE inventory SET min_price_ur = 275, min_price_it = 270, min_price_reg = 261 WHERE name = 'Green Chilli Paste 330GM';
UPDATE inventory SET min_price_ur = 275, min_price_it = 270, min_price_reg = 261 WHERE name = 'Papaya Paste 330GM';
UPDATE inventory SET min_price_ur = 275, min_price_it = 270, min_price_reg = 261 WHERE name = 'Onion Paste 330GM';
UPDATE inventory SET min_price_ur = 1254, min_price_it = 1230, min_price_reg = 1189 WHERE name = 'Acacia Honey 500GM';
UPDATE inventory SET min_price_ur = 500, min_price_it = 490, min_price_reg = 474 WHERE name = 'Onion Paste 750GM';
UPDATE inventory SET min_price_ur = 500, min_price_it = 490, min_price_reg = 474 WHERE name = 'Papaya Paste 750GM';
UPDATE inventory SET min_price_ur = 79, min_price_it = 77, min_price_reg = 75 WHERE name = 'Himalayan Pink Salt Fine Pouch 800GM';
UPDATE inventory SET min_price_ur = 393, min_price_it = 386, min_price_reg = 373 WHERE name = 'Himalayan Pink Salt Glass Grinder 200GM';
UPDATE inventory SET min_price_ur = 70, min_price_it = 69, min_price_reg = 67 WHERE name = 'Himalayan Pink Salt Coarse Pouch 800GM';
UPDATE inventory SET min_price_ur = 148, min_price_it = 145, min_price_reg = 141 WHERE name = 'Himalayan Pink Salt Plastic Grinder 220GM';
UPDATE inventory SET min_price_ur = 95, min_price_it = 93, min_price_reg = 90 WHERE name = 'Himalayan Pink Salt Shaker 500GM';
UPDATE inventory SET min_price_ur = 331, min_price_it = 324, min_price_reg = 324 WHERE name = 'Black Pepper Powder 100GM';
UPDATE inventory SET min_price_ur = 170, min_price_it = 167, min_price_reg = 167 WHERE name = 'Black Pepper Powder 50GM';
UPDATE inventory SET min_price_ur = 142, min_price_it = 139, min_price_reg = 139 WHERE name = 'Chat Masala 100GM';
UPDATE inventory SET min_price_ur = 73, min_price_it = 72, min_price_reg = 72 WHERE name = 'Chat Masala 50GM';
UPDATE inventory SET min_price_ur = 126, min_price_it = 123, min_price_reg = 123 WHERE name = 'Coriander Powder 100GM';
UPDATE inventory SET min_price_ur = 65, min_price_it = 64, min_price_reg = 64 WHERE name = 'Coriander Powder 50GM';
UPDATE inventory SET min_price_ur = 423, min_price_it = 415, min_price_reg = 415 WHERE name = 'Cumin Powder 100GM';
UPDATE inventory SET min_price_ur = 214, min_price_it = 210, min_price_reg = 210 WHERE name = 'Cumin Powder 50GM';
UPDATE inventory SET min_price_ur = 323, min_price_it = 316, min_price_reg = 316 WHERE name = 'Garam Masala 100GM';
UPDATE inventory SET min_price_ur = 170, min_price_it = 167, min_price_reg = 167 WHERE name = 'Garlic Powder 100GM';
UPDATE inventory SET min_price_ur = 102, min_price_it = 100, min_price_reg = 100 WHERE name = 'Garlic Powder 50GM';
UPDATE inventory SET min_price_ur = 250, min_price_it = 245, min_price_reg = 245 WHERE name = 'Ginger Powder 100GM';
UPDATE inventory SET min_price_ur = 130, min_price_it = 127, min_price_reg = 127 WHERE name = 'Ginger Powder 50GM';
UPDATE inventory SET min_price_ur = 45, min_price_it = 44, min_price_reg = 44 WHERE name = 'Dried Fenugreek Leaves (Kasuri Methi) 25 GM';
UPDATE inventory SET min_price_ur = 150, min_price_it = 147, min_price_reg = 147 WHERE name = 'Paprika Powder 50GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Chatpata Tandoori Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Daighi Beef Biryani 120GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Dehli Nihari 120GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Fish Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Fried Fish 100GM';
UPDATE inventory SET min_price_ur = 282, min_price_it = 277, min_price_reg = 277 WHERE name = 'Haleem Mix 300GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Hyderabadi Pulao 130GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Karachi Biryani Masala 120GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Koyla Karhai 80GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Mughlai Qorma 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Peshawari Karhai 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Riwaiti Achar Gosht 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Shahi Seekh Kabab 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Shami Kabab 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Special Tikka 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Traditional Bombay Biryani 120GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Bihari Kabab 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Biryani Masala 90GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Butter Chicken 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'CHICKEN BIRYANI 110GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Chicken Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Curry Kofta Masala 100GM';
UPDATE inventory SET min_price_ur = 307, min_price_it = 301, min_price_reg = 301 WHERE name = 'Curry Powder 200GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Haleem Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Paya Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Tikka Boti 100GM';
UPDATE inventory SET min_price_ur = 170, min_price_it = 167, min_price_reg = 167 WHERE name = 'Vegetable Masala 100GM';
UPDATE inventory SET min_price_ur = 186, min_price_it = 182, min_price_reg = 182 WHERE name = 'Zaiqaydar Dum Qeema 100GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Afghani Malai Boti 30GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Authentic Sindhi Biryani 60GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Bihari Kabab 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Biryani Masala 45GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Butter Chicken 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Chatpata Tandoori Masala 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'CHICKEN BIRYANI 55GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Shami Kabab 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Special Tikka 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Tikka Boti 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Traditional Bombay Biryani 60GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Zaiqaydar Dum Qeema 50GM';
UPDATE inventory SET min_price_ur = 106, min_price_it = 103, min_price_reg = 103 WHERE name = 'Curry Kofta Masala 50GM';
UPDATE inventory SET min_price_ur = 93, min_price_it = 92, min_price_reg = 92 WHERE name = 'Vegetable Masala 50GM';
UPDATE inventory SET min_price_ur = 398, min_price_it = 391, min_price_reg = 391 WHERE name = 'Basmati Rice (Red) 1KG';
UPDATE inventory SET min_price_ur = 1983, min_price_it = 1944, min_price_reg = 1944 WHERE name = 'Basmati Rice (Red) 5KG';
UPDATE inventory SET min_price_ur = 660, min_price_it = 647, min_price_reg = 647 WHERE name = 'Brown Basmati Rice 1.5KG';
UPDATE inventory SET min_price_ur = 331, min_price_it = 324, min_price_reg = 324 WHERE name = 'Economy Rice (Blue) 1KG';
UPDATE inventory SET min_price_ur = 1644, min_price_it = 1612, min_price_reg = 1612 WHERE name = 'Economy Rice (Blue) 5KG';
UPDATE inventory SET min_price_ur = 486, min_price_it = 476, min_price_reg = 476 WHERE name = 'Elite Basmati Rice (Black) 1KG';
UPDATE inventory SET min_price_ur = 2419, min_price_it = 2372, min_price_reg = 2372 WHERE name = 'Elite Basmati Rice (Black) 5KG';
UPDATE inventory SET min_price_ur = 2177, min_price_it = 2134, min_price_reg = 2134 WHERE name = 'Premium Basmati Rice (Silver) 5KG';
UPDATE inventory SET min_price_ur = 437, min_price_it = 429, min_price_reg = 429 WHERE name = 'Premium Basmati Rice (Silver) 1KG';
UPDATE inventory SET min_price_ur = 272, min_price_it = 267, min_price_reg = 267 WHERE name = 'Rozmarrah Rice (Green) 1KG';
UPDATE inventory SET min_price_ur = 1353, min_price_it = 1327, min_price_reg = 1327 WHERE name = 'Rozmarrah Rice (Green) 5KG';
UPDATE inventory SET min_price_ur = 486, min_price_it = 476, min_price_reg = 476 WHERE name = 'Sella Rice (Gold) 1KG';
UPDATE inventory SET min_price_ur = 2419, min_price_it = 2372, min_price_reg = 2372 WHERE name = 'Sella Rice (Gold) 5KG';
UPDATE inventory SET min_price_ur = 1261, min_price_it = 1236, min_price_reg = 1236 WHERE name = 'Classic Rice 5KG';
UPDATE inventory SET min_price_ur = 1019, min_price_it = 999, min_price_reg = 999 WHERE name = 'Kifayat Rice 5KG';
UPDATE inventory SET min_price_ur = 1285, min_price_it = 1260, min_price_reg = 1260 WHERE name = 'Standard Rice 5KG';
UPDATE inventory SET min_price_ur = 403, min_price_it = 395, min_price_reg = 395 WHERE name = 'Jaam-E-Khaas Red Syrup 800ML';
UPDATE inventory SET min_price_ur = 363, min_price_it = 356, min_price_reg = 356 WHERE name = 'Jaam-E-Khaas Ice Cream Syrup 800ML';
UPDATE inventory SET min_price_ur = 410, min_price_it = 402, min_price_reg = 402 WHERE name = 'Assorted Cookies 200GM';
UPDATE inventory SET min_price_ur = 518, min_price_it = 508, min_price_reg = 508 WHERE name = 'Cake Rusk 350GM';
UPDATE inventory SET min_price_ur = 401, min_price_it = 393, min_price_reg = 393 WHERE name = 'Choco Vanilla Cookies 240GM';
UPDATE inventory SET min_price_ur = 335, min_price_it = 328, min_price_reg = 328 WHERE name = 'Classic Chocolate Cookies 200GM';
UPDATE inventory SET min_price_ur = 401, min_price_it = 393, min_price_reg = 393 WHERE name = 'Cumin Delight Cookies 240GM';
UPDATE inventory SET min_price_ur = 485, min_price_it = 475, min_price_reg = 475 WHERE name = 'Naan Khatai 360GM';
UPDATE inventory SET min_price_ur = 401, min_price_it = 393, min_price_reg = 393 WHERE name = 'Strawberry Jam Cookies 240GM';
UPDATE inventory SET min_price_ur = 293, min_price_it = 287, min_price_reg = 287 WHERE name = 'Sugar Puff Pastry 200GM';
UPDATE inventory SET min_price_ur = 206, min_price_it = 202, min_price_reg = 202 WHERE name = 'Tea Rusk 220GM';
UPDATE inventory SET min_price_ur = 501, min_price_it = 492, min_price_reg = 492 WHERE name = 'Assorted Cookies 240GM';
UPDATE inventory SET min_price_ur = 335, min_price_it = 328, min_price_reg = 328 WHERE name = 'Choco Vanilla Cookies 200GM';
COMMIT;